dist: trusty
language: node_js
node_js:
  - "6"
services:
  - postgresql

postgres:
  adapter: postgresql
  database: dms_test
  username: postgres
before_script:
  - psql -c 'create database dms_test;' -U postgres

script:
  - NODE_ENV=test npm run test:server

after_success:
  - npm run coveralls