dist: trusty
language: node_js
node_js:
  - "6"
services:
  - postgresql

postgres:
  adapter: postgresql
  database: travis
  username: postgres
before_script:
  - psql -c 'create database travis;' -U postgres
  - dropdb --if-exists travis && createdb travis
  - npm i -g sequelize-cli
  - npm run migrate_test_db

script:
  - npm test

after_success:
  - npm run coveralls